# -*- coding: utf-8 -*-
# @Time    : 2018/1/31 
# @Author  : LIYUAN134
# @File    : VipCoder.py
# @Commment: 
#            

dic_city = {




    'hen':['zhengzhou','kaifeng','luoyang','pds','anyang','hebi','xinxiang','jiaozuo','puyang','xuchang',
        'luohe','smx','nanyang','shangqiu','xinyang','zhoukou','zmd','henzx'],
    # 'hlj':['herb','qqhe','jixi','hegang','sys','daqing','yich','jms','qth','mdj','heihe','suihua','dxaldq'],
}
dic_city1 = {
    'bj': ['bj'],
    'cq': ['cq'],
    'fj': ['fzh', 'shamen', 'putian', 'sanming', 'quanzhou', 'zhangzhou', 'nanping', 'longyan', 'ningde'],
    '': ['', '', '', '', '', '', '', '', '', '', ],
    '': ['', '', '', '', '', '', '', '', '', '', ],
}
# 公司行业分类
com_trade = {
    'ocD': ['oc45', 'oc44', 'oc46'],  # 电力、热力、燃气》 燃气生产和供应业；电力；水力
    'ocE': ['oc49', 'oc48', 'oc47', 'oc50', ],  # 建筑业》建筑安装；土木工程；房屋建筑；建筑装饰；
    'ocF': ['oc51', 'oc52', ],  # 零售批发》批发业；零售业；
    'ocG': ['oc59', 'oc58', 'oc57', 'oc56', 'oc55', 'oc60', 'oc53', 'oc54', ],
    # 交通邮政》仓储业；装卸搬运与运输代理业；管道运输业；航空运输业；水上运输业；邮政业；铁路运输业；道路运输业
    'ocA': ['oc04', 'oc05', 'oc01', 'oc02', 'oc03', ],  # 农林牧渔》渔业；农林牧服务业；农业；林业；畜牧业
    'ocB': ['oc11', 'oc12', 'oc08', 'oc09', 'oc06', 'oc07', 'oc10', ],
    # 采矿业》开采辅助活动；其它采矿业；黑色金属采选；有色金属采选；煤炭开采；石油和天然气开采；非金属采选
    'ocC': ['oc39', 'oc37',
            'oc38', 'oc43', 'oc42', 'oc41', 'oc40', 'oc22',
            'oc23', 'oc24', 'oc25', 'oc26', 'oc27', 'oc28',
            'oc29', 'oc30', 'oc32', 'oc31', 'oc19', 'oc17',
            'oc18', 'oc15', 'oc16', 'oc13', 'oc14', 'oc21',
            'oc20',
            ],
    # 制造业》专用设备；汽车制造业；金属制品业；通用设备制造业；计算机通讯制造；铁路船舶制造；
    # 电器机械；金属制品；废弃和综合利用；其他制造；仪器仪表制造；造纸和纸质；
    # 印刷和记录；文体美工体育；石油加工；化学原料；医药制造；化学纤维
    # 橡胶和塑料；非金属矿物；有色金属冶炼；黑色金属冶炼；皮革毛皮；纺织业；
    # 纺织服装；酒饮料茶；烟草制造；农副食品加工；食品制造；家具制造；
    # 木材加工
    'ocL': ['oc71', 'oc72', ],  # 租赁和商务服务》租赁；商务服务
    'ocM': ['oc73', 'oc74', 'oc75', ],  # 科学研究和技术》研究和试验；专业技术服务；科技推广
    'ocN': ['oc78', 'oc77', 'oc76', ],  # 水力环境公共设施》公共设施；生态保护;水力管理
    'ocO': ['oc79', 'oc80', 'oc81', ],  # 居民服务》居民服务；机动车；其它服务业
    'ocH': ['oc62', 'oc61', ],  # 住宿和餐饮》餐饮；住宿
    'ocI': ['oc64', 'oc65', 'oc63', ],  # 信息传输软件信息》互联网；软件和信息；电信广播
    'ocJ': ['oc67', 'oc66', 'oc69', 'oc68', ],  # 金融业》资本市场服务；货币金融；其他金融；保险业
    'ocK': ['oc70'],  # 房地产业》房地产业  目前只有一个
    'ocT': ['oc96', ],  # 国际组织》国际组织 目前只有一个
    'ocQ': ['oc83', 'oc84', ],  # 卫生和社会工作》 卫生；社会工作
    'ocP': ['oc82'],  # 教育》教育 目前只有一个
    'ocS': ['oc95', 'oc94', 'oc93', 'oc92', 'oc91', 'oc90', ],
    # 公共管理社会保障》基层群众；群众团体；社会保障；人民协办；国家机构；共产党机关
    'ocR': ['oc88', 'oc89', 'oc86', 'oc87', 'oc85', ],  # 文化体育娱乐》体育；娱乐业；广播电视；文化艺术业；新闻出版

}
# 注册资金
com_values = {
    '-r0100': '<100万',
    '-r100200': '100-200万',
    '-r200500': '200-500万',
    '-r5001000': '500-1000万',
    '-r1000': '>1000万',
}
# 注册时间
com_times = {
    '-e01': '一年以内',
    '-e015': '1-5年',
    '-e510': '5-10年',
    '-e1015': '10-15年',
    '-e15': '15年以上',
}
# 企业状态
com_status = {
    '-s1': '在业',
    '-s2': '存续',
    '-s3': '吊销',
    '-s4': '注销',
    '-s5': '迁出',
}


def decode(key):
    values = {
        'ah': u'安徽',
        'js': u'江苏',
        'snx': u'陕西',

        'hefei': u'合肥',
        'wuhu': u'芜湖',
        'bangbu': u'蚌埠',
        'huainan': u'淮南',
        'mas': u'马鞍山',
        'huaibei': u'淮北',
        'tongling': u'铜陵',
        'anqing': u'安庆',
        'huangshan': u'黄山',
        'chuzhou': u'滁州',
        'fuyang': u'阜阳',
        'suzhou': u'宿州',
        'liuan': u'六安',
        'bozhou': u'亳州',
        'chizhou': u'池州',
        'xuancheng': u'宣城',

        'bj': u'北京',
        'cq': u'重庆',

        'fj': u'福建',
        'fzh': u'福州',
        'shamen': u'厦门',
        'putian': u'莆田',
        'sanming': u'三明',
        'quanzhou': u'泉州',
        'zhangzhou': u'漳州',
        'nanping': u'南平',
        'longyan': u'龙岩',
        'ningde': u'宁德',

        'gd': u'广东',
        'shenzhen': u'深圳',
        'dongguan': u'东莞',
        'zhongshan': u'中山',
        'guangzhou': u'广州',
        'shaoguan': u'韶关',
        'zhuhai': u'珠海',
        'shantou': u'汕头',
        'foshan': u'佛山',
        'jiangmen': u'江门',
        'zhanjiang': u'湛江',
        'maoming': u'茂名',
        'zhaoqing': u'肇庆',
        'huizhou': u'惠州',
        'meizhou': u'梅州',
        'shanwei': u'汕尾',
        'heyuan': u'河源',
        'yangjiang': u'阳江',
        'qingyuan': u'清远',
        'chaozhou': u'潮州',
        'jieyang': u'揭阳',
        'yunfu': u'云浮',

        'gs': u'甘肃',
        'jyg': u'嘉峪关',
        'lanzhou': u'兰州',
        'jinchang': u'金昌',
        'baiyin': u'白银',
        'tianshui': u'天水',
        'wuwei': u'武威',
        'zhangye': u'张掖',
        'pingliang': u'平凉',
        'jiuquan': u'酒泉',
        'qingyang': u'庆阳',
        'dingxi': u'定西',
        'longnan': u'陇南',
        'lxhz': u'临夏回族',
        'gnzz': u'甘南藏族',

        'gx': u'广西',
        'nanning': u'南宁',
        'liuzhou': u'柳州',
        'guilin': u'桂林',
        'wuzhou': u'梧州',
        'beihai': u'北海',
        'fcg': u'防城港',
        'qinzhou': u'钦州',
        'guigang': u'贵港',
        'yul': u'玉林',
        'baise': u'白色',
        'hezhou': u'贺州',
        'hechi': u'河池',
        'laibin': u'来宾',
        'laibin': u'崇左',

        'gz': u'贵州',
        'guiyang': u'贵阳',
        'lps': u'六盘水',
        'zunyi': u'遵义',
        'anshun': u'安顺',
        'bijie': u'毕节',
        'tongren': u'铜仁',
        'qxnbyz': u'黔西南布伊',
        'qdnz': u'黔东南州',
        'qnbyz': u'黔南布伊',

        'han': u'海南',
        'haikou': u'海口',
        'sanya': u'三亚',
        'hanzx': u'海南自治',

        'heb': u'河北',
        'sjz': u'石家庄',
        'tangshan': u'唐山',
        'qhd': u'秦皇岛',
        'handan': u'邯郸',
        'xingtai': u'邢台',
        'baoding': u'保定',
        'zjk': u'张家口',
        'chengde': u'承德',
        'cangzhou': u'沧州',
        'langfang': u'廊坊',
        'hengshui': u'衡水',

        'hen': u'河南',
        'zhengzhou': u'郑州',
        'kaifeng': u'开封',
        'luoyang': u'洛阳',
        'pds': u'平顶山',
        'anyang': u'安阳',
        'hebi': u'鹤壁',
        'xinxiang': u'新乡',
        'jiaozuo': u'焦作',
        'puyang': u'濮阳',
        'xuchang': u'许昌',
        'luohe': u'漯河',
        'smx': u'三门峡',
        'nanyang': u'南阳',
        'shangqiu': u'商丘',
        'xinyang': u'信阳',
        'zhoukou': u'周口',
        'zmd': u'驻马店',
        'henzx': u'河南直辖',

        'hlj': u'黑龙江',
        'herb': u'哈尔滨',
        'qqhe': u'齐齐哈尔',
        'jixi': u'鸡西',
        'hegang': u'鹤岗',
        'sys': u'双鸭山',
        'daqing': u'大庆',
        'yich': u'伊春',
        'jms': u'佳木斯',
        'qth': u'七台河',
        'mdj': u'牡丹江',
        'heihe': u'黑河',
        'suihua': u'绥化',
        'dxaldq': u'大兴安岭',

        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',
        # '': u'',






        'wuxi': u'无锡',
        'xuzhou': u'徐州',
        'changzhou': u'常州',
        'szh': u'苏州',
        'nantong': u'南通',
        'nanjing': u'南京',
        'wuxi': u'无锡',
        'lyg': u'连云港',
        'huaian': u'淮安',
        'yancheng': u'盐城',
        'yangzhou': u'扬州',
        'zhenjiang': u'镇江',
        'tzh': u'泰州',
        'suqian': u'宿迁',

        'xian': u'西安',
        'tongchuan': u'铜川',

        'ocS': u'公共管理社会保障',
        'ocD': u'电力、热力、燃气',
        'ocE': u'建筑业',
        'ocF': u'零售批发',
        'ocG': u'交通邮政',
        'ocA': u'农林牧渔',
        'ocB': u'采矿业',
        'ocC': u'制造业',
        'ocL': u'租赁和商务服务',
        'ocM': u'科学研究和技术',
        'ocN': u'水力环境公共设施',
        'ocO': u'居民服务',
        'ocH': u'住宿和餐饮',
        'ocI': u'信息传输软件信息',
        'ocJ': u'金融业',
        'ocK': u'房地产业',
        'ocT': u'国际组织',
        'ocQ': u'卫生和社会工作',
        'ocP': u'教育',
        'ocS': u'公共管理社会保障',
        'ocR': u'文化体育',
        'oc45': u'燃气生产和供应业',
        'oc44': u'电力',
        'oc46': u'水力',
        'oc49': u'建筑安装',
        'oc48': u'土木工程',
        'oc47': u'房屋建筑',
        'oc50': u'建筑装饰',
        'oc51': u'批发业',
        'oc52': u'零售业',
        'oc59': u'仓储业',
        'oc58': u'装卸搬运与运输代理业',
        'oc57': u'管道运输业',
        'oc56': u'航空运输业',
        'oc55': u'水上运输业',
        'oc60': u'邮政业',
        'oc53': u'铁路运输业',
        'oc54': u'道路运输业',
        'oc04': u'渔业',
        'oc05': u'农林牧服务业',
        'oc01': u'农业',
        'oc02': u'林业',
        'oc03': u'畜牧业',
        'oc11': u'开采辅助活动',
        'oc12': u'其它采矿业',
        'oc08': u'黑色金属采选',
        'oc09': u'有色金属采选',
        'oc06': u'煤炭开采',
        'oc07': u'石油和天然气开采',
        'oc10': u'非金属采选',
        'oc35': u'专用设备',
        'oc36': u'汽车制造业',
        'oc33': u'金属制品业',
        'oc34': u'通用设备制造业',
        'oc39': u'计算机通讯制造',
        'oc37': u'铁路船舶制造',
        'oc38': u'电器机械',
        'oc43': u'金属制品',
        'oc42': u'废弃和综合利用',
        'oc41': u'其他制造',
        'oc40': u'仪器仪表制造',
        'oc22': u'造纸和纸质',
        'oc23': u'印刷和记录',
        'oc24': u'文体美工体育',
        'oc25': u'石油加工',
        'oc26': u'化学原料',
        'oc27': u'医药制造',
        'oc28': u'化学纤维',
        'oc29': u'橡胶和塑料',
        'oc30': u'非金属矿物',
        'oc32': u'有色金属冶炼',
        'oc31': u'黑色金属冶炼',
        'oc19': u'皮革毛皮',
        'oc17': u'纺织业',
        'oc18': u'纺织服装',
        'oc15': u'酒饮料茶',
        'oc16': u'烟草制造',
        'oc13': u'农副食品加工',
        'oc14': u'食品制造',
        'oc21': u'家具制造',
        'oc20': u'木材加工',
        'oc71': u'租赁',
        'oc72': u'商务服务',
        'oc73': u'研究和试验',
        'oc74': u'专业技术服务',
        'oc75': u'科技推广',
        'oc78': u'公共设施',
        'oc77': u'生态保护',
        'oc76': u'水力管理',
        'oc79': u'居民服务',
        'oc80': u'机动车',
        'oc81': u'其它服务业',
        'oc62': u'餐饮',
        'oc61': u'住宿',
        'oc64': u'互联网',
        'oc65': u'软件和信息',
        'oc63': u'电信广播',
        'oc67': u'资本市场服务',
        'oc66': u'货币金融',
        'oc69': u'其他金融',
        'oc68': u'保险业',
        'oc70': u'房地产业',
        'oc96': u'国际组织',
        'oc83': u'卫生',
        'oc84': u'社会工作',
        'oc82': u'教育',
        'oc95': u'基层群众',
        'oc94': u'群众团体',
        'oc93': u'社会保障',
        'oc92': u'人民协办',
        'oc91': u'国家机构',
        'oc90': u'共产党机关',
        'oc88': u'体育',
        'oc89': u'娱乐业',
        'oc86': u'广播电视',
        'oc87': u'文化艺术',
        'oc85': u'新闻出版',
        '-r0100': u'0-100万',
        '-r100200': u'100万-200万',
        '-r200500': u'200万-500万',
        '-r5001000': u'500万-1000万',
        '-r1000': u'1000万以上',
        '-e01': u'成立一年以内',
        '-e015': u'成立1-5年',
        '-e510': u'成立5-10年',
        '-e1015': u'成立10-15年',
        '-e15': u'成立15年以上',
        '-s1': u'在业',
        '-s2': u'存续',
        '-s3': u'吊销',
        '-s4': u'注销',
        '-s5': u'迁出',

    }.get(key, key)
    return values


dic_city_finish = {
    'ah': [
        'hefei',
        'wuhu',
        'bangbu',
        'huainan',
        'mas',
        'huaibei',
        'tongling',
        'anqing',
        'huangshan',
        'chuzhou',
        'fuyang',
        'suzhou',
        'liuan',
        'bozhou',
        'chizhou',
        'xuancheng',
    ],

    'js': [
        'nanjing',
        'wuxi',
        'xuzhou',
        'changzhou',
        'szh',
        'nantong',
        'lyg',
        'huaian',
        'yancheng',
        'yangzhou',
        'zhenjiang',
        'tzh',
        'suqian',
    ],
    'gd': [
        'shenzhen',
        'dongguan',
        'zhongshan',
        'guangzhou',
        'shaoguan',
        'zhuhai',
        'shantou',
        'foshan',
        'jiangmen',
        'zhanjiang',
        'maoming',
        'zhaoqing',
        'huizhou',
        'meizhou',
        'shanwei',
        'heyuan',
        'yangjiang',
        'qingyuan',
        'chaozhou',
        'jieyang',
        'yunfu',
    ],
    # 'bj': ['bj'],
    # 'cq': ['cq'],
    # 'fj': ['fzh', 'shamen', 'putian', 'sanming', 'quanzhou', 'zhangzhou', 'nanping', 'longyan', 'ningde'],
    # 'snx': ['xian', 'tongchuan', ]
    # 'gd': ['shenzhen', 'dongguan', 'zhongshan', 'guangzhou', 'shaoguan', 'zhuhai', 'shantou', 'foshan',
    #        'jiangmen', 'zhanjiang', 'maoming', 'zhaoqing', 'huizhou', 'meizhou', 'shanwei', 'heyuan',
    #        'yangjiang', 'qingyuan', 'chaozhou', 'jieyang', 'yunfu'],
    'gs': ['dingxi', 'longnan', 'lxhz', 'gnzz', ],
    # 'gx':['nanning','liuzhou','guilin','wuzhou','beihai','fcg','qinzhou','guigang','yul','baise','hezhou','hechi',
    #      'laibin','laibin'],
    # 'han': ['haikou', 'sanya', 'hanzx'],
# 'gz':['guiyang','lps','zunyi','anshun','bijie','tongren','qxnbyz','qdnz','qnbyz',],
# 'heb':['sjz','tangshan','qhd','handan','xingtai','baoding','zjk','chengde','cangzhou','langfang','hengshui'],
}
